In [1]:
import torch

In [2]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
type(my_tensor)

torch.Tensor

In [4]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad = True)

In [7]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


In [8]:
x = torch.empty(size = (3,3), dtype=torch.int32)

In [9]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [10]:
x1 = torch.empty(size = (3,3), dtype=torch.float32)

In [11]:
x1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
zero = torch.zeros((3,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
rand = torch.rand(3,3)
rand

tensor([[0.0507, 0.4518, 0.3747],
        [0.1757, 0.3851, 0.1265],
        [0.0820, 0.4292, 0.8117]])

In [14]:
one = torch.ones((5,5))
one

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
eye = torch.eye(5,5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
x = torch.arange(0, 20, 2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
x = torch.linspace(0.1, 1, 10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [18]:
x = torch.empty(size=(1, 5)).normal_(mean = 0, std = 1)
x

tensor([[-0.0029, -1.7273, -0.4645, -0.7485,  0.1191]])

In [19]:
x = torch.empty(size=(1, 10)).uniform_(0, 1)

In [20]:
x

tensor([[0.2955, 0.9916, 0.8324, 0.4834, 0.9078, 0.5442, 0.1320, 0.7345, 0.6576,
         0.1543]])

In [21]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [28]:
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [29]:
import numpy as np

In [30]:
np_1 = np.zeros((5, 5))
np_1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
tensor_n = torch.from_numpy(np_1)
tensor_n

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [33]:
np_t = tensor_n.numpy()
np_t

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
print(x, y)

tensor([1, 2, 3]) tensor([9, 8, 7])


In [36]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

tensor([10., 10., 10.])


In [38]:
z = x + y
z

tensor([10, 10, 10])

In [40]:
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

In [41]:
z = x - y
z

tensor([-8, -6, -4])

In [42]:
t = torch.zeros(3)
t

tensor([0., 0., 0.])

In [43]:
t.add_(x)

tensor([1., 2., 3.])

In [47]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [48]:
z = x ** 2
z

tensor([1, 4, 9])

In [49]:
z = x > 0
z

tensor([True, True, True])

In [53]:
z = x < 0
z

tensor([False, False, False])

In [54]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)

In [55]:
print(x1)
print(x2)

tensor([[0.2717, 0.9013, 0.0052, 0.9070, 0.4086],
        [0.4787, 0.8818, 0.1761, 0.0284, 0.6651]])
tensor([[0.7084, 0.2298, 0.6739],
        [0.3074, 0.4831, 0.3138],
        [0.3533, 0.2202, 0.9428],
        [0.9463, 0.9841, 0.9135],
        [0.8745, 0.8178, 0.7851]])


In [56]:
print(x3)

tensor([[1.6870, 1.7258, 1.6202],
        [1.2810, 1.1467, 1.3134]])


In [57]:
x4 = x1.mm(x2)
x4

tensor([[1.6870, 1.7258, 1.6202],
        [1.2810, 1.1467, 1.3134]])

In [62]:
matrix_exp = torch.rand(3, 3)
matrix_exp.matrix_power(10)

tensor([[222.2265, 252.4551, 250.7297],
        [196.8070, 223.5779, 222.0499],
        [236.6496, 268.8402, 267.0029]])

In [64]:
z = x * y
z

tensor([ 9, 16, 21])

In [65]:
z = torch.dot(x, y)
z

tensor(46)

In [66]:
batch = 32
n = 10
m = 20
p = 30

In [72]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

In [73]:
out_bmm = torch.bmm(tensor1, tensor2)
out_bmm

tensor([[[5.2722, 4.9896, 6.2298,  ..., 4.6415, 4.8057, 6.0612],
         [4.5555, 5.3126, 5.2276,  ..., 4.9052, 4.4415, 5.2003],
         [5.6340, 5.3678, 6.7233,  ..., 5.7883, 5.6521, 6.6623],
         ...,
         [4.6723, 4.8617, 5.2137,  ..., 4.8889, 4.4001, 5.9146],
         [5.0133, 4.7657, 5.0046,  ..., 4.7059, 5.2901, 5.8329],
         [4.9973, 4.6107, 6.3361,  ..., 4.6842, 4.6242, 5.7867]],

        [[6.1921, 6.4519, 5.0062,  ..., 4.1852, 6.1227, 4.3712],
         [5.6830, 6.5085, 4.7807,  ..., 4.0086, 6.1797, 3.9663],
         [3.4889, 5.3741, 3.4540,  ..., 2.9427, 4.3585, 3.4611],
         ...,
         [4.4227, 5.3087, 4.1572,  ..., 3.1184, 4.3342, 3.7696],
         [6.5138, 7.9498, 6.3873,  ..., 4.2833, 7.3370, 6.5010],
         [4.2373, 5.0162, 4.1819,  ..., 2.5982, 4.8507, 3.6224]],

        [[4.8714, 4.8852, 4.8213,  ..., 4.6781, 3.3977, 4.2899],
         [5.5345, 6.7545, 5.1947,  ..., 5.5496, 5.2409, 4.5693],
         [4.9720, 5.2764, 5.3958,  ..., 4.9906, 4.1245, 4.

In [74]:
x1 = torch.rand((6,6))
x2 = torch.rand((1, 6))
z = x1 - x2

In [75]:
z

tensor([[-0.1887,  0.1685,  0.0477,  0.1396,  0.1567, -0.5240],
        [-0.0576,  0.0568, -0.1456,  0.6457,  0.0977, -0.1075],
        [-0.7849,  0.2626, -0.2940,  0.4309, -0.4512, -0.8387],
        [-0.2768,  0.1065,  0.5786,  0.5457, -0.1482, -0.4735],
        [-0.7631, -0.1499,  0.3053,  0.4489, -0.3576, -0.1236],
        [-0.6484, -0.3717, -0.2469,  0.0980, -0.2389, -0.2448]])

In [76]:
z = x1 ** x2
z

tensor([[0.7454, 0.7982, 0.7253, 0.7800, 0.8608, 0.4002],
        [0.8677, 0.7312, 0.5788, 0.9881, 0.8195, 0.7934],
        [0.1537, 0.8487, 0.4096, 0.9120, 0.3393, 0.0551],
        [0.6622, 0.7621, 0.9927, 0.9543, 0.6321, 0.4502],
        [0.1773, 0.5748, 0.8703, 0.9190, 0.4417, 0.7788],
        [0.2975, 0.2485, 0.4732, 0.7567, 0.5543, 0.6678]])

In [80]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [82]:
values, ind = torch.max(x, dim=0)

In [83]:
values, ind

(tensor(3), tensor(2))

In [84]:
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [86]:
z = torch.argmax(x, dim=0)
z

tensor(2)

In [87]:
z = torch.argmin(z, dim=0)
z

tensor(0)

In [88]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor(2.)

In [89]:
z = torch.eq(x, y)
z

tensor([False, False, False])

In [90]:
torch.sort(y, dim=0, descending=False)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))

In [91]:
torch.sort(y, dim=0, descending=True)

torch.return_types.sort(
values=tensor([9, 8, 7]),
indices=tensor([0, 1, 2]))

In [92]:
torch.clamp(x, min=0)

tensor([1, 2, 3])

In [94]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
z = torch.any(x)
x

tensor([ True, False,  True,  True,  True])

In [95]:
x

tensor([ True, False,  True,  True,  True])

In [96]:
x = torch.all(x)
print(x)
print(z)

tensor(False)
tensor(True)


In [97]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [98]:
print(x[0])

tensor([0.0934, 0.3551, 0.1683, 0.5733, 0.4787, 0.3606, 0.8956, 0.4635, 0.7200,
        0.7462, 0.3820, 0.0325, 0.6375, 0.9528, 0.7802, 0.6014, 0.2617, 0.7743,
        0.3116, 0.7755, 0.8868, 0.8394, 0.4410, 0.4261, 0.1747])


In [100]:
print(x[1:4])

tensor([[0.3932, 0.1321, 0.4517, 0.9985, 0.8486, 0.2122, 0.0019, 0.1290, 0.5211,
         0.4342, 0.7772, 0.7883, 0.2106, 0.6283, 0.3047, 0.9443, 0.9454, 0.1736,
         0.9675, 0.4859, 0.7620, 0.0719, 0.2631, 0.1908, 0.1702],
        [0.5617, 0.5899, 0.9665, 0.0434, 0.3395, 0.0421, 0.4858, 0.9485, 0.9987,
         0.9183, 0.7277, 0.1798, 0.1668, 0.1845, 0.9235, 0.4625, 0.9106, 0.3860,
         0.2258, 0.0937, 0.5429, 0.1515, 0.5121, 0.1071, 0.5314],
        [0.8415, 0.6569, 0.1188, 0.4925, 0.6229, 0.8390, 0.1256, 0.5913, 0.2734,
         0.6180, 0.3934, 0.9231, 0.7656, 0.8541, 0.3068, 0.5907, 0.7329, 0.6922,
         0.9666, 0.3488, 0.2980, 0.8401, 0.9433, 0.9808, 0.1333]])


In [102]:
print(x[-1].shape, x[0].shape)

torch.Size([25]) torch.Size([25])


In [103]:
print(x[:, 0])

tensor([0.0934, 0.3932, 0.5617, 0.8415, 0.8703, 0.8568, 0.6247, 0.5674, 0.1151,
        0.9117])


In [104]:
print(x[2,0:10])

tensor([0.5617, 0.5899, 0.9665, 0.0434, 0.3395, 0.0421, 0.4858, 0.9485, 0.9987,
        0.9183])


In [106]:
x[0, 0] = 100
x[0]

tensor([1.0000e+02, 3.5512e-01, 1.6833e-01, 5.7334e-01, 4.7872e-01, 3.6060e-01,
        8.9556e-01, 4.6347e-01, 7.1999e-01, 7.4621e-01, 3.8205e-01, 3.2512e-02,
        6.3751e-01, 9.5279e-01, 7.8015e-01, 6.0143e-01, 2.6168e-01, 7.7427e-01,
        3.1161e-01, 7.7555e-01, 8.8678e-01, 8.3936e-01, 4.4104e-01, 4.2609e-01,
        1.7467e-01])

In [107]:
x = torch.arange(10)
ind = [2, 5, 8]
x, ind

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), [2, 5, 8])

In [108]:
x[ind]

tensor([2, 5, 8])

In [110]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows,cols], x.shape)

tensor([0.4998, 0.0143]) torch.Size([3, 5])


In [111]:
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])

tensor([0, 1, 9])


In [112]:
print(x[x.remainder(2) == 0])

tensor([0, 2, 4, 6, 8])


In [118]:
print(torch.where(x > 5, x, x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [119]:
print(torch.tensor([0, 0, 1, 2, 2, 3, 6]).unique())

tensor([0, 1, 2, 3, 6])


In [120]:
print(x.ndimension())

1


In [121]:
print(x.numel())

10


In [122]:
x = torch.arange(9)
x_3 = x.view(3, 3)
x_3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [124]:
print(x)
print(x_3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [125]:
x_33 = x.reshape(3,3)
x_33

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [127]:
y = x_33.t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [130]:
print(y.reshape(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [131]:
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [135]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [136]:
z = x1.view(-1)
z

tensor([0.3911, 0.9249, 0.4100, 0.2422, 0.3742, 0.0347, 0.9950, 0.8220, 0.3920,
        0.4288])

In [137]:
z1

tensor([10., 10., 10.])

In [138]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)

In [140]:
print(x[0])
print(z.shape)
print(z[0])
print(z.shape)

tensor([[0.2913, 0.0689, 0.5367, 0.5361, 0.6650],
        [0.0595, 0.3845, 0.5973, 0.2811, 0.1594]])
torch.Size([64, 10])
tensor([0.2913, 0.0689, 0.5367, 0.5361, 0.6650, 0.0595, 0.3845, 0.5973, 0.2811,
        0.1594])
torch.Size([64, 10])


In [143]:
z = x.permute(0, 2, 1)

In [144]:
print(z.shape)

torch.Size([64, 5, 2])


In [146]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
print(x.unsqueeze(0).shape)

torch.Size([1, 10])


In [148]:
print(x.unsqueeze(0))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [149]:
print(x.unsqueeze(1).shape)

torch.Size([10, 1])


In [150]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)

In [151]:
x

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [153]:
z = x.squeeze(1)
print(z.shape)

torch.Size([1, 10])
